# frozen_string_literal: true

# Verification example — Spec 7 (Input Staging + Artifacts). Runs OFFLINE, no model.
#
# Demonstrates the deliverable shape end to end: stage a baseline + additional files into
# the run's Virtual sandbox, then render a digest ARTIFACT from a trusted developer template.
#
#   ruby -Ilib examples/artifact_from_template.rb
#
# This is the mechanics of use case #2 (file-upload -> artifact) with the "improve" step
# left out (that needs an agent — see Spec 8 / examples/inbox_digest_task.rb).
require "nexo"

class BuildDigest < Nexo::Workflow
  # Default sandbox is :virtual (safe, in-memory) — nothing touches the host.
  def call(payload)
    # Stage the provided files (baseline + extras + the template) into the run sandbox.
    stage(payload[:files])
    emit(:staged, files: payload[:files].map { |f| f[:path] })

    # Render a NAMED artifact from a TRUSTED developer template (ERB runs Ruby — never
    # render model output or uploads here).
    artifact("digest.md",
      from: "/workspace/digest.md.erb",
      locals: {title: payload[:title], baseline: sandbox.read("/workspace/baseline.md")})

    {ok: true}
  end
end

if __FILE__ == $PROGRAM_NAME
  Nexo::RunStore::Memory.reset! if defined?(Nexo::RunStore::Memory)

  files = [
    {path: "baseline.md", content: "- item one\n- item two\n"},
    {path: "extra.md", content: "- item three\n"},
    # a trusted, developer-authored ERB template (checked into the repo, not uploaded)
    {path: "digest.md.erb", content: <<~ERB}
      # <%= title %>

      Baseline captured:
      <%= baseline %>
      Generated by Nexo.
    ERB
  ]

  run = BuildDigest.run(title: "Weekly Digest", files: files)

  puts "run status: #{run.status}"
  digest = run.artifacts.find { |a| (a["name"] || a[:name]) == "digest.md" }
  puts "---- artifact: digest.md ----"
  puts(digest["content"] || digest[:content])
  # In a Rails Action, a controller would read run.artifacts here to show/download the result.
end
